# Generated by Django 5.0.3 on 2024-11-11 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="category_pictures/"
                    ),
                ),
            ],
            options={"verbose_name": "一级分类", "verbose_name_plural": "一级分类表",},
        ),
        migrations.CreateModel(
            name="SubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="subcategory_pictures/"
                    ),
                ),
                ("sale_properties", models.JSONField(blank=True, null=True)),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="category.category",
                    ),
                ),
            ],
            options={"verbose_name": "二级分类", "verbose_name_plural": "二级分类表",},
        ),
    ]
