# Generated by Django 5.0.3 on 2024-11-11 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account", models.CharField(max_length=50)),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="user_avatars/"),
                ),
                ("birthday", models.DateField(blank=True, null=True)),
                ("city_code", models.CharField(max_length=20)),
                ("gender", models.CharField(max_length=10)),
                ("mobile", models.CharField(max_length=15)),
                ("nickname", models.CharField(max_length=50)),
                ("profession", models.CharField(max_length=100)),
                ("province_code", models.CharField(max_length=20)),
                ("token", models.CharField(max_length=100)),
            ],
            options={"verbose_name": "用户", "verbose_name_plural": "用户表",},
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=255)),
                (
                    "address_tags",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("city_code", models.CharField(max_length=20)),
                ("contact", models.CharField(max_length=50)),
                ("county_code", models.CharField(max_length=20)),
                ("full_location", models.CharField(max_length=255)),
                ("postal_code", models.CharField(blank=True, max_length=20, null=True)),
                ("province_code", models.CharField(max_length=20)),
                ("receiver", models.CharField(max_length=50)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to="user.user",
                    ),
                ),
            ],
            options={"verbose_name": "收货地址", "verbose_name_plural": "收货地址表",},
        ),
    ]
