# Generated by Django 5.0.3 on 2024-11-11 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("category", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("desc", models.TextField(blank=True, null=True)),
                (
                    "picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="author_pictures/"
                    ),
                ),
                ("place", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={"verbose_name": "作家", "verbose_name_plural": "作家表",},
        ),
        migrations.CreateModel(
            name="Publisher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="publisher_logos/"
                    ),
                ),
                ("desc", models.TextField(blank=True, null=True)),
                (
                    "picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="publisher_pictures/"
                    ),
                ),
                ("place", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={"verbose_name": "出版商", "verbose_name_plural": "出版商表",},
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ISBN", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("desc", models.TextField()),
                ("discount", models.IntegerField()),
                ("old_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("inventory", models.IntegerField()),
                ("collect_count", models.IntegerField(default=0)),
                ("sales_count", models.IntegerField(default=0)),
                ("comment_count", models.IntegerField(default=0)),
                ("main_pictures", models.JSONField(blank=True, null=True)),
                (
                    "authors",
                    models.ManyToManyField(related_name="books", to="product.author"),
                ),
                (
                    "subcategory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="books",
                        to="category.subcategory",
                    ),
                ),
                (
                    "publisher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="books",
                        to="product.publisher",
                    ),
                ),
            ],
            options={"verbose_name": "书籍", "verbose_name_plural": "书籍表",},
        ),
    ]
