# Generated by Django 5.0.3 on 2024-12-06 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_alter_book_main_pictures"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="main_pictures",
            field=models.ImageField(blank=True, null=True, upload_to="book_pictures/"),
        ),
    ]
