# Generated by Django 5.0.3 on 2024-12-06 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_alter_book_main_pictures"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="main_pictures",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
