# Generated by Django 5.0.3 on 2024-12-06 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_alter_book_main_pictures"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="publish_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
