# Generated by Django 5.1.2 on 2024-12-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="buyer_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_time_type",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="order",
            name="pay_channel",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="order",
            name="pay_type",
            field=models.IntegerField(default=0),
        ),
    ]
