# Generated by Django 5.0.3 on 2024-11-11 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("product", "0001_initial"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.IntegerField(default=1)),
                (
                    "original_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("current_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="cart_pictures/"
                    ),
                ),
                ("post_fee", models.DecimalField(decimal_places=2, max_digits=5)),
                ("stock", models.IntegerField()),
                (
                    "books",
                    models.ManyToManyField(related_name="carts", to="product.book"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carts",
                        to="user.user",
                    ),
                ),
            ],
            options={"verbose_name": "购物车", "verbose_name_plural": "购物车表",},
        ),
    ]
